### ISSUE TITLE
Test 11 fails : python-test_dyson (SEGFAULT)

### ISSUE THREAD

**Issue by GingrasO** [jasonkaye/libdlr#1]
Dear developers,

When performing `make test`, test 11 fails with a segfault.

Here is what is outputted in LastTest.log:
```
11/12 Testing: python-test_dyson
11/12 Test: python-test_dyson
Command: "/cm/shared/sw/nix/store/1mnbhnjnzymysnh60yf60wzkpi15554f-python-3.8.12-view/bin/python3.8" "-m" "nose" "./test/test_dyson.py" "-v"
Directory: /mnt/home/ogingras/Work/Github/libdlr/cbuild/pydlr
"python-test_dyson" start time: Dec 17 14:43 EST 
Output:
----------------------------------------------------------
/cm/shared/sw/nix/store/1mnbhnjnzymysnh60yf60wzkpi15554f-python-3.8.12-view/lib/python3.8/site-packages/nose/plugins/manager.py:394: RuntimeWarning: Unable to load plugin answer-testing = yt.utilities.answer_testing.framework:AnswerTesting: Trying to re-register the builtin cmap 'cubehelix'.
  warn("Unable to load plugin %s: %s" % (ep, e), 
test_dyson.test_dyson_and_volterra_matsubara ... ok
test_dyson.test_dyson_dlr ... 
<end of output>
Test time =   4.82 sec 
----------------------------------------------------------
Test Failed.
```
Apparently [this is a problem with the newer versions of matplotlib](https://stackoverflow.com/questions/67969047/error-trying-to-re-register-the-builtin-cmap-cubehelix-when-trying-to-import). I could get rid of it by downgrading to matplotlib 3.0.1. Any way to avoid this downgrade? 

Thanks

**Comment by HugoStrand** [comment]
Dear Olivier,

Thank you for reporting the issue.

One option would be for you to update the python package `yt`. According to the link you provided it is actually this module that causes the error not `matplotlib`. The fix in the `yt` package was merged in March 2021, see https://github.com/yt-project/yt/pull/3149

I think this problem is unrelated to `pydlr`, please reopen this case if updating `yt` does not solve the issue.

Best regards,
Hugo
